### ISSUE TITLE
Please allow multiply labels in dictionary config

### ISSUE THREAD

**Issue by jhercher** [fusepool/fusepool-sma#3]
Hi. 

It would be helpful if you can define multiply labels for matching in the dictionary configuration. For instance SKOS has skos:prefLabel and skos:altLabel. I wish I could configure sth. like `skos:prefLabel ; skos:altLabel`.

At the moment all properties for matching need to be mapped to one property, such as rdfs:label for example (cf. screenshot).
![conf_dictionary](https://cloud.githubusercontent.com/assets/941635/3279261/70647390-f3f3-11e3-8f0a-7a0169379e22.png)

Having this feature would make it more efficient to use thesauruses as dictionary for matching.

cheers, 
Johannes

**Comment by gaborremenyi** [comment]
Hi Johannes,

The issue you raised, unfortunately goes beyond simply allowing multiple labels in the configuration of the engine. I will have to modify the enhancer to handle synonyms (labels sharing the same uri), and implementing this could take some time. That said, I still see the value behind it, so I'll try to implement it as soon as possible, given that the project is nearing its end. I'll keep you posted.

Cheers,
Gabor

**Comment by jhercher** [comment]
Hi Gabor,

thank you for your reply. I like to add that this is not a critical issue at the moment. As I wrote one could overcome this issue by modify the input data and map all labels to one property. Nevertheless it would be a useful feature for future releases.

Cheers, 
Johannes

**Comment by gaborremenyi** [comment]
Hi Johannes,

I implemented the necessary changes for handling synonyms and committed it to GitHub (along with some other changes that were due anyway). I did some tests it using the existing disease ontology, and the engine works as expected. Although if you find any problem, please let me know. You can find the repo here: https://github.com/fusepool/fusepool-sma

You will see that there is a new configuration field - (Synonym Field, right under the Label Field) - where you can define where the synonyms should come from. It is optional, though, so if you leave it empty, the engine will work the same as before.
![config](https://cloud.githubusercontent.com/assets/2647400/3337833/11b61070-f852-11e3-81f2-7da9d1049e4d.png)

In case of the disease ontology I have a preferred label (<code>rdfs:label</code>) for each disease, and multiple synonyms (<code>oboInOwl:hasExactSynonym</code>).

``` xml
<owl:Class rdf:about="http://purl.obolibrary.org/obo/DOID_10811">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">nasal cavity cancer</rdfs:label>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050615"/>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A respiratory system cancer that is located_in the nasal cavity.</obo:IAO_0000115>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">DOID:10811</oboInOwl:id>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ICD9CM:160.0</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI:C4918</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">SNOMEDCT_2010_1_31:187832001</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">SNOMEDCT_2010_1_31:363422006</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">SNOMEDCT_2010_1_31:93917007</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">UMLS_CUI:C0728864</oboInOwl:hasDbXref>
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">disease_ontology</oboInOwl:hasOBONamespace>
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">malignant neoplasm of nasal cavities</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">malignant neoplasm of nasal cavities NOS (disorder)</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">malignant neoplasm of nasal cavity, NOS</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">malignant tumor of nasal cavity (disorder)</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">malignant tumor of the nasal cavity</oboInOwl:hasExactSynonym>
    </owl:Class>
```

I did not test it with SKOS, but in your case the label field should be <code>skos:prefLabel</code> and the synonym field should be <code>skos:altLabel</code>.

Cheers,
Gabor
