### ISSUE TITLE
Building Dictionary Annotator Enhancer Engine: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by retog** [fusepool/fusepool-sma#4]
Moved from: https://github.com/fusepool/fusepool-platform/issues/42

[INFO] Building Fusepool Dictionary Annotator Enhancer Engine 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ enhancer.engines.dictionaryannotator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ enhancer.engines.dictionaryannotator ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-scr-plugin:1.16.0:scr (generate-scr-scrdescriptor) @ enhancer.engines.dictionaryannotator ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by gaborremenyi** [comment]
Readding the explicit version to osgi-compendium in pom.xml resolved the issue.
